### ISSUE TITLE
ask for some help

### ISSUE THREAD

**Issue by huanghuaihuai** [TU-Darmstadt-APQ/AD9910-arduino#1]
Hello,Can you give me a contact number or e-mail? I want to ask you about your project.

**Comment by lakodarmstadt** [comment]
lars.pause@physik.tu-darmstadt.de

**Comment by PatrickBaus** [comment]
Fixed by [e5b680c](https://github.com/TU-Darmstadt-APQ/AD9910-arduino/commit/e5b680c0394f8dbc046767d4a00d563bd4635b4e).
